"""fresh schema

Revision ID: 5f9211454061
Revises: 
Create Date: 2026-04-29 10:31:37.105759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f9211454061'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_detection_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='network, system, web, or unified'),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False, comment='LOW, MEDIUM, HIGH, CRITICAL'),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('global_status', sa.String(length=20), nullable=True),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('attack_category', sa.String(length=100), nullable=True),
    sa.Column('vulnerability_type', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attack_probability', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('network_prediction', sa.JSON(), nullable=True),
    sa.Column('system_prediction', sa.JSON(), nullable=True),
    sa.Column('web_prediction', sa.JSON(), nullable=True),
    sa.Column('unified_result', sa.JSON(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('model_status', sa.String(length=20), nullable=False),
    sa.Column('degraded_mode', sa.Boolean(), nullable=False),
    sa.Column('missing_inputs', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_detection_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_detection_events_attack_type'), ['attack_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_detection_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_detection_events_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_detection_events_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_detection_events_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_detection_events_target'), ['target'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_detection_events_user_id'), ['user_id'], unique=False)

    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('training_data_size', sa.Integer(), nullable=True),
    sa.Column('training_date', sa.DateTime(), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_type', 'version', name='unique_model_version')
    )
    op.create_table('ai_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('ai_detection_event_id', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.String(length=50), nullable=False),
    sa.Column('prediction_confidence', sa.Float(), nullable=False),
    sa.Column('corrected_label', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='network, system, web, or unified'),
    sa.Column('original_risk_level', sa.String(length=20), nullable=True),
    sa.Column('corrected_risk_level', sa.String(length=20), nullable=True),
    sa.Column('used_for_training', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('training_timestamp', sa.DateTime(), nullable=True),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.Column('high_confidence_wrong', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_detection_event_id'], ['ai_detection_events.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_feedback_ai_detection_event_id'), ['ai_detection_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_feedback_feedback_timestamp'), ['feedback_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_feedback_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_feedback_used_for_training'), ['used_for_training'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_feedback_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('target',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('open_ports',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('services',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('os_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('vulnerabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('findings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_scans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_scan_type'), ['scan_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_target'), ['target'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('scans_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('mode')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('settings_key_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('settings_key_key'), ['key'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('scans_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_scans_user_id'))
        batch_op.drop_index(batch_op.f('ix_scans_target'))
        batch_op.drop_index(batch_op.f('ix_scans_status'))
        batch_op.drop_index(batch_op.f('ix_scans_scan_type'))
        batch_op.drop_index(batch_op.f('ix_scans_created_at'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('findings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('vulnerabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('os_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('services',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('open_ports',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('target',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('ai_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_feedback_used_for_training'))
        batch_op.drop_index(batch_op.f('ix_ai_feedback_scan_id'))
        batch_op.drop_index(batch_op.f('ix_ai_feedback_feedback_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ai_feedback_ai_detection_event_id'))

    op.drop_table('ai_feedback')
    op.drop_table('ai_models')
    with op.batch_alter_table('ai_detection_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_detection_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_detection_events_target'))
        batch_op.drop_index(batch_op.f('ix_ai_detection_events_source_type'))
        batch_op.drop_index(batch_op.f('ix_ai_detection_events_scan_id'))
        batch_op.drop_index(batch_op.f('ix_ai_detection_events_risk_level'))
        batch_op.drop_index(batch_op.f('ix_ai_detection_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_detection_events_attack_type'))

    op.drop_table('ai_detection_events')
    # ### end Alembic commands ###
